# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_SP7021) += \
	sunplus-sp7021-demo-v3.dtb
dtb-$(CONFIG_SOC_SP7021) += \
	sp7021-ltpp3g2-sunplus.dtb
dtb-$(CONFIG_SOC_SP7021) += \
	sunplus-sp7021-ltpp3.dtb
